### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by iworks** [pentatonicfunk/pot-similarity#2]
./vendor/bin/pot-similarity find:similar /var/virtuals/incsub/wp-content/plugins/ultimate-brand/languages/ub.pot 
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/gettext/gettext/src/Translation.php on line 180
PHP Stack trace:
PHP   1. {main}() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/pot-similarity:0
PHP   2. require() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/pot-similarity:4
PHP   3. Symfony\Component\Console\Application->run() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/console.php:22
PHP   4. Symfony\Component\Console\Application->doRun() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/symfony/console/Application.php:129
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/symfony/console/Application.php:222
PHP   6. Symfony\Component\Console\Command\Command->run() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/symfony/console/Application.php:918
PHP   7. PotSimilarity\Commands\FindSimilarity->execute() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/symfony/console/Command/Command.php:252
PHP   8. PotSimilarity\Library\Parser->parse() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Commands/FindSimilarity.php:45
PHP   9. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:44
PHP  10. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:90
PHP  11. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:90
PHP  12. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:90
PHP  13. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:90
PHP  14. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:90
PHP  15. PotSimilarity\Library\Parser->findSimilar() /var/virtuals/incsub/wp-content/plugins/ultimate-branding/vendor/pentatonicfunk/pot-similarity/Library/Parser.php:90

**Comment by pentatonicfunk** [comment]
@iworks do you have `XDebug` enabled, if so , please try to add this on `xdebug.ini` 
```
xdebug.max_nesting_level=3000
```
as a workaround.
While im trying to figure out alternative methods. Unless you have yummy PR 😋
